language: scala
script:
   - sbt clean coverage test
after_success:
   - sbt coveralls
   - sbt coverageReport
   - sbt coverageAggregate
   - sbt codacyCoverage
jdk:
   - oraclejdk8
cache:
   directories:
   - $HOME/.m2
   - $HOME/.ivy2
   - $HOME/.sbt
